default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: postgres
  host: localhost
  template: template0

development:
  <<: *default
  database: deleatur_development

test:
  <<: *default
  database: deleatur_test
  min_messages: WARNING

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  encoding: utf8
  pool: 20
  min_messages: WARNING